### PR TITLE
Upgrade odfe version to 1.13.0

### PR DESCRIPTION
**Pull request by VijayanB**
Upgrade to ES 7.10.2

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jmazanec15 — APPROVED** [review]
LGTM!

**Review by vamshin — COMMENTED** [review]
You might want to change here as well https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/gradle.properties#L16.

Even though this field is not used but just to keep it consistent.

**Comment by VijayanB** [comment]
> You might want to change here as well https://github.com/opendistro-for-elasticsearch/k-NN/blob/master/gradle.properties#L16.
> 
> Even though this field is not used but just to keep it consistent.

Ack.

**Review by vamshin — APPROVED** [review]
LGTM! Thanks for the changes.

**Pull request merged**
